name: CI Workflow

on:
  #push:
   # paths:
    #  - "app/**"
      #- "tests/**"
      #- ".github/workflows/02-ci.yml"

 # pull_request:
    #branches:
     # - main

  workflow_dispatch:

jobs:
  verify2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Run tests
        run: |
          echo "Starting CI tests..."
          sleep 10
          python -m unittest discover -s tests -p "test*.py" -v