name: CI and ECR Push Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    name: Verify + Build + Fix + Scan + Push
    runs-on: ubuntu-latest

    env:
      ECR_REPOSITORY: ci-cd
      LOCAL_IMAGE_NAME: tiny-health-app

    steps:
      # ---------------------------------
      # Checkout Repository
      # ---------------------------------
      - name: Check out repository
        uses: actions/checkout@v4

      # ---------------------------------
      # Setup Python
      # ---------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # ---------------------------------
      # Run Tests
      # ---------------------------------
      - name: Run tests
        run: python -m unittest discover -s tests -v

      # ---------------------------------
      # Upgrade Python Tools
      # ---------------------------------
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # ---------------------------------
      # Upgrade Requirements if exists
      # ---------------------------------
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      # ---------------------------------
      # Build Docker Image
      # ---------------------------------
      - name: Build Docker image locally
        run: docker build --pull -t ${LOCAL_IMAGE_NAME}:latest .

      # ---------------------------------
      # Scan Docker Image
      # ---------------------------------
      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tiny-health-app:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          scanners: vuln

      # ---------------------------------
      # Configure AWS Credentials
      # ---------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECRACCESS }}
          aws-secret-access-key: ${{ secrets.ECRSECRETACCESS }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ---------------------------------
      # Login to Amazon ECR
      # ---------------------------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------------------------
      # Generate Dynamic Tag
      # ---------------------------------
      - name: Set image tag
        id: image-tag
        run: |
          TODAY="$(date -u +%Y-%m-%d)"
          IMAGE_TAG="${TODAY}-${GITHUB_RUN_ID}"
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      # ---------------------------------
      # Tag and Push to ECR
      # ---------------------------------
      - name: Tag and Push Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.image-tag.outputs.image_tag }}
        run: |
          IMAGE_URI="$ECR_REGISTRY/${ECR_REPOSITORY}:$IMAGE_TAG"

          docker tag ${LOCAL_IMAGE_NAME}:latest $IMAGE_URI
          docker push $IMAGE_URI